
# ──────────────────────────────────────────────────────────────────────────────
# 1. Paths
# ──────────────────────────────────────────────────────────────────────────────
[Paths]
csv_path             = ""        # Folder containing TrackMate CSV exports
mask_path            = ""        # Folder of per-frame PNG masks (dimensions must match video)
comdet_path          = ""        # (Optional) Folder with ComDet CSVs for fixed-particle analysis
output_folder_name   = "SF2"     # Name for the pipeline’s output directory

# ──────────────────────────────────────────────────────────────────────────────
# 2. Toggle Flags
# ──────────────────────────────────────────────────────────────────────────────
[Toggle]
use_gap_fixed           = true   # Interpolate short detection gaps before reclassification
filter_by_binding_prop  = true   # Drop tracks whose bound+constrained fraction is out of range
run_visualizer          = true   # Generate colored overlay videos of track behaviors
run_MSD_calculations    = true   # Compute and plot Mean Squared Displacement (MSD) curves
run_fixed_particle      = true   # Execute experimental ComDet-based rebinding analysis
bacteria_analysis       = true   # Aggressive overlap filtering for single-molecule (bacterial) data

# ──────────────────────────────────────────────────────────────────────────────
# 3. Track-Sorting
# ──────────────────────────────────────────────────────────────────────────────
[Track-Sorting]
allowed_gap_max           = 4     # Max consecutive missing frames before splitting a track
allowed_track_length_min  = 6     # Discard tracks shorter than this (frames)
allowed_track_length_max  = 5000  # Discard tracks longer than this (frames)
dist_range                = 5     # Frames before/after for inter-frame distance calc
allowed_overlap           = 30    # Overlap frames threshold for collision resolution
concurrent_max            = 10    # Max consecutive frames with >1 simultaneous spots

# ──────────────────────────────────────────────────────────────────────────────
# 4. Bound-Classification
# ──────────────────────────────────────────────────────────────────────────────
[Bound-Classification]
distance_threshold         = 2.0   # px: relaxed binding step threshold over ±4-frame window
distance_threshold_strict  = 1.2   # px: strict binding threshold (low false-pos) for high-framerate

# ──────────────────────────────────────────────────────────────────────────────
# 5. Gaps-&-Fixes
# ──────────────────────────────────────────────────────────────────────────────
[Gaps-and-Fixes]
min_time_strict            = 0      # frames: min length for strict-binding; shorter ⇒ constrained
min_time_constrained       = 4      # frames: min for constrained diffusion; shorter ⇒ free
min_time_diffusion         = 0      # frames: min for free diffusion; shorter ⇒ context reclassification
max_bound_gapFill          = 4      # frames: gap allowance to merge into strict-binding
min_prop_binding           = 0.00   # fraction: min track-level bound+constrained to keep
max_prop_binding           = 1.01   # fraction: max track-level bound+constrained to keep
allowed_gapTotal           = 1000000# total gap-fill ops per track (to discard over-blinking)

# ──────────────────────────────────────────────────────────────────────────────
# 6. Rebind-Analysis
# ──────────────────────────────────────────────────────────────────────────────
[Rebind-Analysis]
rebind_distance_same          = 1.0     # px: same-site rebinding distance threshold
rebind_distance_diff          = 4.0     # px: nearby-site rebinding distance threshold
min_time_bound_strict         = 4       # frames: min strict-binding for rebinding logs
min_time_bound_constrained    = 3       # frames: min constrained-binding for rebinding logs
min_time_rebinding_relaxed    = 0       # frames: relaxed min diffusion between bindings
min_time_rebinding_strict     = 10      # frames: strict min diffusion to avoid flicker
min_time_diffusion            = 0       # frames: min diffusion overall for rebinding
min_time_diffusion_subsequent = 1       # frames: min diffusion after bind to count subsequent
max_time_rebinding            = 50      # frames: window to search for rebinding
max_time_constrained          = 100000  # frames: cap for constrained-binding in rebinding

# ──────────────────────────────────────────────────────────────────────────────
# 7. MSD-Analysis
# ──────────────────────────────────────────────────────────────────────────────
[MSD-Analysis]
time_interval_ms     = 10.0    # ms: frame interval (must match acquisition)
pixel_size_um        = 0.094   # µm: physical pixel size for D calculations
use_brownian_only    = true    # force anomalous exponent α = 1 (pure Brownian fit)

# ──────────────────────────────────────────────────────────────────────────────
# 8. Visualizer
# ──────────────────────────────────────────────────────────────────────────────
[Visualizer]
tail_effect_enabled  = true    # draw motion-blur “tails” for moving spots
spot_diameter        = 6       # px diameter of each spot in the overlay

# ──────────────────────────────────────────────────────────────────────────────
# 9. Rebind-Fixed-Particle
# ──────────────────────────────────────────────────────────────────────────────
[Rebind-Fixed-Particle]
allowed_spot_overlap = 0.10    # max fractional area overlap for ComDet spots
