[path]
csv_path = 'F:\DataDump\Sim_BP_FR\test\Images2\AnalysisRebind' # csv from trackmate
mask_path = 'F:\DataDump\Sim_BP_FR\test\segmented'  # *.png

output_folder_name = 'SA'

[toggle]
use_gap_fixed = true # for rebind-analysis to use gap-fixed
filter_by_binding_prop = true # filter tracks after gap-fixes
run_visualizer = true # run visualizer after analysis
run_MSD_calculations = true # run MSD calculations after analysis

[track-sorting]
allowed_gap_max = 10
allowed_track_length_min = 60
allowed_track_length_max = 20000
dist_range = 5
allowed_overlap = 30 # allowed total repeated frames in tracks in a cell, eliminate all tracks if exceeds
concurrent_max = 10 # max concurrent frames in *different* tracks in a cell, eliminate the frames if exceeds.

[bound-classification]
distance_threshold = 2.6
distance_threshold_strict = 1.2

[gaps-and-fixes]
min_time_strict = 4
min_time_constrained = 3
min_time_diffusion = 3
max_bound_gapFill = 4
min_prop_binding = 0.08 # for both constricted and strict, filter condition after gap-fixes
max_prop_binding = 0.99 # filter also for all-bound tracks, most-likely dirt

[rebind-analysis]
rebind_distance_same = 1.0 # Determines rebinds to same particles < parameter
rebind_distance_diff = 4.0 # Determines rebinds to diff particles > parameter
min_time_bound_strict = 4
min_time_bound_constrained = 3
min_time_rebinding_relaxed = 0
min_time_rebinding_strict = 10
min_time_diffusion = 0
min_time_diffusion_subsequent = 1 # minimum time required for subsequent event after diffusion
max_time_rebinding = 50 # after which it will be counted unsuccessful
max_time_constrained = 50 # after which it will be counted unsuccessful
